# Generated by Django 5.0.6 on 2026-06-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la ruta')),
                ('route_data', models.JSONField(verbose_name='Datos de la ruta (nodos/aristas)')),
                ('total_length', models.FloatField(verbose_name='Longitud total (m)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_routes', to='plans.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Ruta de evacuación',
                'verbose_name_plural': 'Rutas de evacuación',
                'ordering': ['total_length'],
            },
        ),
    ]
