# Generated by Django 5.0.6 on 2026-06-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('svg', 'SVG')], max_length=10, verbose_name='Tipo de archivo')),
                ('file', models.FileField(upload_to='exports/', verbose_name='Archivo exportado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_files', to='plans.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Archivo exportado',
                'verbose_name_plural': 'Archivos exportados',
                'ordering': ['-created_at'],
            },
        ),
    ]
