# Generated by Django 5.0.6 on 2026-06-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('extinguisher', 'Extintor'), ('exit', 'Salida EXIT'), ('first_aid', 'Botiquín'), ('alarm', 'Alarma'), ('meeting_point', 'Punto de encuentro'), ('fire_hose', 'Manguera contra incendios')], max_length=30, verbose_name='Tipo de señal')),
                ('position_x', models.FloatField(verbose_name='Posición X')),
                ('position_y', models.FloatField(verbose_name='Posición Y')),
                ('rotation', models.FloatField(default=0, verbose_name='Rotación (°)')),
                ('auto_placed', models.BooleanField(default=False, verbose_name='Colocada automáticamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='plans.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Señal',
                'verbose_name_plural': 'Señales',
            },
        ),
    ]
