# Generated by Django 5.0.6 on 2026-06-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del plano')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Croquis original')),
                ('scale', models.FloatField(default=1.0, verbose_name='Escala (px/cm)')),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal (carta)'), ('vertical', 'Vertical')], default='horizontal', max_length=20, verbose_name='Orientación')),
                ('canvas_data', models.JSONField(blank=True, null=True, verbose_name='Datos del canvas (Fabric.js)')),
                ('is_vectorized', models.BooleanField(default=False, verbose_name='Vectorizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
