# Generated by Django 5.0.6 on 2026-06-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/', verbose_name='Imagen procesada')),
                ('vector_data', models.JSONField(blank=True, null=True, verbose_name='Datos vectorizados')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='plans.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Trabajo de procesamiento',
                'verbose_name_plural': 'Trabajos de procesamiento',
            },
        ),
    ]
